# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: terrascan
    id: terrascan_linux_amd64
    main: ./cmd/terrascan/main.go
    ldflags: -s -w -extldflags=-static
    env:
      - CGO_ENABLED=1
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - linux
    goarch:
      - amd64
  - binary: terrascan
    id: terrascan_linux_386
    main: ./cmd/terrascan/main.go
    ldflags: -s -w -extldflags=-static
    env:
      - CGO_ENABLED=1
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - linux
    goarch:
      - 386
  - binary: terrascan
    id: terrascan_darwin
    main: ./cmd/terrascan/main.go
    ldflags: -s -w
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - darwin
    goarch:
      - amd64
  - binary: terrascan
    id: terrascan_windows
    main: ./cmd/terrascan/main.go
    ldflags: -s -w
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
