terrascan_api_key: terrakey
terrascan_container_image: accurics/terrascan:1.5.0
use_debug: true
secret_name: terrascancerts
config_name: terrascanconfig
name: terrascan
persistence:
  enabled: false
  existingclaim: terrascanPvc
