terrascan_api_key: terrakey
terrascan_container_image: accurics/terrascan:1.5.0
use_debug: true
secret_name: terrascan_certs
ca_bundle: {{ .Files.Get "data/ca.crt" | b64enc }}
config_name: terrascan_config
name: terrahook
persistence:
  enabled: false
  existingclaim: terrascanPvc
webhook:
  mode: true
  name: www.terrahook.com
  failurePolicy: fail
  sideEffects: None
  admissionReviewVersions:
    - "v1"
    - "v1beta1"
  apiGroups:
    - "apps"
    - ""
  resources:
    - "deployments"
    - "pods"
  apiVersions:
    - "*"
  operations:
    - CREATE
